package org.myOrg.myProject.ModemGUI;

import java.util.Observable;

/*******************************************************************************
 * Top level class which contains all the high-level modem status.
 * @author Daniel Hals
 ******************************************************************************/
public class MainStatus extends javax.swing.JPanel {
    
    /***************************************************************************
     * Creates new form MainStatus
     **************************************************************************/
    public MainStatus() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(210, 662));
        setPreferredSize(new java.awt.Dimension(210, 662));
        setRequestFocusEnabled(false);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(MainStatus.class, "MainStatus.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGap(122, 122, 122)
                .addContainerGap(918, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    /***************************************************************************
     * Updates class when notified of change
     * 
     * @param o 
     * @param arg
     **************************************************************************/
    public void update(Observable o, Object arg) {
    }
}
